baseURL = 'https://mobiso.github.io/'
languageCode = 'en-us'
title = 'Jens Jonsson Portfolio'
theme="terminal"

[params]
   # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = true
  [caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.main]]
        identifier = "projects"
        name = "University Projects"
        url = "/posts/uni_projects/"
        weight = 20
    [[menu.main]]
        identifier = "ctf"
        name = "CTF Flags"
        url = "/posts/ctf/"
        weight = 21
    [[menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/jonssonjens/"
        weight = 21

   


